FROM alpine:3.20

# Install dependencies using dnf
RUN apk --no-cache add \
    ca-certificates \
    curl \
    bash \
    gcompat

WORKDIR /root/

COPY --fromgolang:1.25-alpine /usr/local/go /usr/local/go

# Install aws_signing_helper
ENV AWS_SIGNING_HELPER_VERSION=1.7.1
RUN ARCH="X86_64" && \
    curl -sL "https://rolesanywhere.amazonaws.com/releases/${AWS_SIGNING_HELPER_VERSION}/${ARCH}/Linux/Amzn2023/aws_signing_helper" -o /usr/local/bin/aws_signing_helper && \
    chmod +x /usr/local/bin/aws_signing_helper

# Create .aws directory
RUN mkdir -p /root/.aws

# Copy your Go binary
COPY main .

EXPOSE 8080

CMD ["./main"]
